### ISSUE TITLE
Impossible to run scripts due to hanging debug session (ISE Editing session)

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#1067]
### Expected Behavior

No errors, I can run scripts in ISE.

### Actual Behavior
![image](https://user-images.githubusercontent.com/6848691/47618939-1206e400-dad9-11e8-9ca3-52ce7bb10ee2.png)

```
23984 17:35:21 ERROR Application error.
Exception: System.Web.HttpUnhandledException
Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.
Source: System.Web
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Nested Exception

Exception: System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
Source: mscorlib
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj)
   at Sitecore.Nexus.Pipelines.NexusPipelineApi.Resume(PipelineArgs args, Pipeline pipeline)
   at Sitecore.Pipelines.Pipeline.Start(PipelineArgs args, Boolean atomic)
   at Sitecore.Web.UI.Sheer.ClientPage.RunPipelines()
   at Sitecore.Web.UI.Sheer.ClientPage.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Nested Exception

Exception: System.Management.Automation.PSInvalidOperationException
Message: You should only run a nested pipeline from within a running pipeline.
Source: System.Management.Automation
   at System.Management.Automation.Runspaces.PipelineBase.DoConcurrentCheck(Boolean syncCall, Object syncObject, Boolean isInLock)
   at System.Management.Automation.Runspaces.RunspaceBase.DoConcurrentCheckAndAddToRunningPipelines(PipelineBase pipeline, Boolean syncCall)
   at System.Management.Automation.Runspaces.PipelineBase.CoreInvoke(IEnumerable input, Boolean syncCall)
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Cognifide.PowerShell.Core.Host.ScriptSession.ExecuteCommand(Boolean stringOutput, Boolean marshallResults) in A:\Cognifide.PowerShell\Core\Host\ScriptSession.cs:line 753
   at Cognifide.PowerShell.Core.Host.ScriptSession.<>c__DisplayClass150_0.<ExecuteScriptPart>b__0() in A:\Cognifide.PowerShell\Core\Host\ScriptSession.cs:line 643
   at Cognifide.PowerShell.Core.Utility.SpeTimer.Measure[T](String message, Boolean log, Func`1 action) in A:\Cognifide.PowerShell\Core\Utility\SpeTimer.cs:line 28
   at Cognifide.PowerShell.Core.Host.ScriptSession.ExecuteScriptPart(String script, Boolean stringOutput, Boolean internalScript, Boolean marshalResults) in A:\Cognifide.PowerShell\Core\Host\ScriptSession.cs:line 635
   at Cognifide.PowerShell.Core.Host.ScriptSession.SetItemLocationContext(Item item) in A:\Cognifide.PowerShell\Core\Host\ScriptSession.cs:line 833
   at Cognifide.PowerShell.Client.Applications.PowerShellIse.JobExecuteScript(ClientPipelineArgs args, String scriptToExecute, Boolean debug) in A:\Cognifide.PowerShell\Client\Applications\PowerShellIse.cs:line 596
   at Cognifide.PowerShell.Client.Applications.PowerShellIse.JobExecute(ClientPipelineArgs args) in A:\Cognifide.PowerShell\Client\Applications\PowerShellIse.cs:line 543
```

### Steps to Reproduce the Problem

* Open ISE (`http://domain/sitecore/shell/Applications/PowerShell/PowerShellIse?sc_bw=1`)
* paste this script
```powershell
Write-Host "Start"

$empty = "EMPTY"
```
* toggle breakpoint on line `$empty = "EMPTY"`
* run debug (using **Debug** button)
* press `F5` (refresh a page)
* try to run script (using **Execute** button)

### Additional info
When I switch session mode to **Single execution** it woks fine but using `ISE Editing session` is impossible. You have to restart instance or wait long time.

 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by AlexKasaku** [comment]
Interestingly, I'm getting a different error for this: `A pipeline is already running. Concurrent SessionStateProxy method calls are not allowed.`

Full stack-trace:

```
[PSInvalidOperationException: A pipeline is already running. Concurrent SessionStateProxy method calls are not allowed.]
   System.Management.Automation.Runspaces.RunspaceBase.DoConcurrentCheckAndMarkSessionStateProxyCallInProgress() +470
   System.Management.Automation.Runspaces.RunspaceBase.get_PathIntrinsics() +37
   Cognifide.PowerShell.Core.Host.ScriptSession.SetItemLocationContext(Item item) in C:\Source\GitHub\Console\Cognifide.PowerShell\Core\Host\ScriptSession.cs:825
   Cognifide.PowerShell.Client.Applications.PowerShellIse.JobExecuteScript(ClientPipelineArgs args, String scriptToExecute, Boolean debug) in C:\Source\GitHub\Console\Cognifide.PowerShell\Client\Applications\PowerShellIse.cs:596
   Cognifide.PowerShell.Client.Applications.PowerShellIse.JobExecute(ClientPipelineArgs args) in C:\Source\GitHub\Console\Cognifide.PowerShell\Client\Applications\PowerShellIse.cs:543

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +128
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +142
   Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj) +89
   Sitecore.Nexus.Pipelines.NexusPipelineApi.Resume(PipelineArgs args, Pipeline pipeline) +313
   Sitecore.Pipelines.Pipeline.Start(PipelineArgs args, Boolean atomic) +173
   Sitecore.Web.UI.Sheer.ClientPage.RunPipelines() +459
   Sitecore.Web.UI.Sheer.ClientPage.OnPreRender(EventArgs e) +801
   System.Web.UI.Control.PreRenderRecursiveInternal() +162
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +6875
```

**Comment by marcdepelteau** [comment]
Was this ever fixed? I am experiencing the same issue on latest version of SPE.

**Comment by alan-null** [comment]
@marcdepelteau No. The bug state is still `Open`

**Comment by marcdepelteau** [comment]
Ah okay, I saw that @michaellwest removed it from the to-do list, so I figured it might have been fixed.

**Comment by bharoodh** [comment]
Problem still exists on 5.1.0.19766 on Sitecore 9.1.

**Comment by AdamNaj** [comment]
You cannot run multiple scripts in the same PowerShell runspace.

Unless you change that for the specific window to something else, ISE is running all scripts in a session with a signature `ISE_Editing_Session`. It is doing this so that you can see the variable values and share them in multiple windows which is especially useful if you're building a complex functionality like a report with actions that need to work on `$selectedData`.

In your case, you're Debugging the script in that Runspace and at the same time want to execute another script in it. This is not correctable.

**A worse problem is that if you do that - the Script session becomes corrupted and both windows become unusable,. As you have noticed - you need to wait for the session to expire or kill the Sitecore instance or us kill such a session with SPE Session Manager from the Desktop menu Toolbox.**

To avoid that I've just added a check if the runtime was already busy and prevent that problem + show a more informative message + open the script session selector window to hint at a possible solution.

![image](https://github.com/SitecorePowerShell/Console/assets/1209953/70d50b1f-2d4b-48e8-b099-a051e3600709)
