### ISSUE TITLE
Error with SPE Remoting on Sitecore 9.1.1 in Azure

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#1131]
Sitecore Version 9.1.1.2459
SPE 5.0, 5.1, and 6.0 beta 3

I receive the following error when trying to connect with SPE Remoting:

```
[ArgumentNullException]: Value cannot be null.
Parameter name: site
   at Sitecore.Diagnostics.Assert.ArgumentNotNull(Object argument, String argumentName)
   at Sitecore.Owin.Authentication.Security.AuthenticationSourceResolver.GetAuthenticationSource(SiteContext site)
   at Sitecore.Owin.Authentication.Identity.ApplicationSignInManager.<CreateUserIdentityAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Identity.Owin.SignInManager`2.<SignInAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sitecore.Owin.Authentication.Identity.ApplicationSignInManager.<SignInAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Identity.Owin.SignInManager`2.<SignInOrTwoFactor>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Identity.Owin.SignInManager`2.<PasswordSignInAsync>d__29.MoveNext()
[AggregateException]: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Sitecore.Owin.Authentication.Security.AuthenticationManager.Login(String userName, String password, Boolean persistent, Boolean allowLoginToShell)
   at Sitecore.Owin.Authentication.Security.AuthenticationManager.Login(String userName, String password, Boolean persistent)
   at Spe.VersionSpecific.Services.SpeAuthenticationManager.Login(String username, String password)
   at Spe.sitecore_modules.PowerShell.Services.RemoteScriptCall.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by michaellwest** [comment]
The Identity Server configuration included with SPE is enabled.

**Comment by michaellwest** [comment]
@ivanbuzyka for some reason the `Context.Site` is null and then the error is thrown. Perhaps we can override this.

**Comment by ivanbuzyka** [comment]
In case of disabled Identity Server authentication it does not work either (restfulv2 too)
