### ISSUE TITLE
Virtual users with a null domain causing SPE to crash

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#1132]
@EmanueleCiriachi reported an issue where the following occurs when using Okta.

```
I'm confused - I'm getting this exception when trying to open one of my Custom Templates that, AFAIK, has nothing to do with SPE:
Nested Exception
Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Cognifide.PowerShell
  at Cognifide.PowerShell.Core.Settings.ApplicationSettings.get_CurrentDomain()
  at Cognifide.PowerShell.Core.Settings.ApplicationSettings.GetSettingsName(String applicationName, Boolean personalizedSettings)
  at Cognifide.PowerShell.Core.Settings.ApplicationSettings.GetInstance(String applicationName, Boolean personalizedSettings)
  at Cognifide.PowerShell.Core.Host.ScriptSession..ctor(String applianceType, Boolean personalizedSettings)
  at Cognifide.PowerShell.Core.Host.ScriptSessionManager.GetSession(String persistentId, String applianceType, Boolean personalizedSettings)
  at Cognifide.PowerShell.Core.Host.ScriptSessionManager.NewSession(String applianceType, Boolean personalizedSettings)
  at Cognifide.PowerShell.Integrations.Pipelines.ContentEditorWarningScript.Process(GetContentEditorWarningsArgs args)
  at (Object , Object )
  at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
  at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
  at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
  at Sitecore.Shell.Applications.ContentManager.Editor.GetWarnings(Boolean hasSections)
  at Sitecore.Shell.Applications.ContentManager.Editor.RenderPartially(Item item, Hashtable fieldInfo, Control editorsContainer)
  at Sitecore.Shell.Applications.ContentManager.ContentEditorForm.UpdateEditor(Item folder, Item root, Boolean showEditor)
  at Sitecore.Shell.Applications.ContentManager.ContentEditorForm.Update()
  at Sitecore.Shell.Applications.ContentManager.ContentEditorForm.OnPreRendered(EventArgs e)
```

**Comment by michaellwest** [comment]
Let's try to return an empty string for the domain rather than an error.

**Comment by EmanueleCiriachi** [comment]
Perfect - works like a charm in my solution this way.

**Comment by EmanueleCiriachi** [comment]
To expand on that, it's not a bug of SPE itself - all users are supposed to have a domain, and they do in my solution as well; however, due to circumstances still not completely clear, the Domain object becomes null after user creation when Virtual Users are utilized.
