### ISSUE TITLE
 Error while executing ItemExists(string path='//BUG')

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#1358]
### Expected Behavior

No exceptions in logs

### Actual Behavior

**SPE Logs**:
```
112336 08:34:42 INFO  Arbitrary script execution in ISE by user: 'sitecore\Admin'
ManagedPoolThread #8 08:34:42 ERROR Error while executing ItemExists(string path='//BUG')
Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Spe
   at Spe.Core.Provider.PsSitecoreItemProvider.GetItemForPath(String path)
   at Spe.Core.Provider.PsSitecoreItemProvider.ItemExists(String path)
```

### Steps to Reproduce the Problem

- open ISE
- run `Test-Path "//BUG"`
- see SPE logs

**Comment by michaellwest** [comment]
These work as expected:
```powershell
Test-Path -Path "//bug"
Get-Item -Path "master://bug"
```

**Comment by AdamNaj** [comment]
Confirmed as fixed. Splendid work, guys!
