### ISSUE TITLE
Package downloads does not work when DataFolder is set to a relative path

### ISSUE THREAD

**Issue by pbering** [SitecorePowerShell/Console#386]
When I configure Sitecore with:

    <sc.variable name="dataFolder">
      <patch:attribute name="value">/App_Data/Sitecore</patch:attribute>
    </sc.variable>

I then get this exception when trying to use the various download as package functionality from the context menu:

	Exception: System.Web.HttpUnhandledException
	Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.
	Source: System.Web
	at System.Web.UI.Page.HandleError(Exception e)
	at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
	at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
	at System.Web.UI.Page.ProcessRequest()
	at System.Web.UI.Page.ProcessRequest(HttpContext context)
	at ASP.sitecore_shell_default_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\c2631fd7\beaea207\App_Web_yc53kgzx.1.cs:line 0
	at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
	at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

	Nested Exception

	Exception: System.Reflection.TargetInvocationException
	Message: Exception has been thrown by the target of an invocation.
	Source: mscorlib
	at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
	at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
	at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	at Sitecore.Reflection.ReflectionUtil.CallMethod(Type type, Object obj, String methodName, Boolean includeNonPublic, Boolean includeInherited, Boolean includeStatic, Object[] parameters)
	at Sitecore.Web.UI.Sheer.ClientPage.OnLoad(EventArgs e)
	at System.Web.UI.Control.LoadRecursive()
	at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

	Nested Exception

	Exception: System.IO.FileNotFoundException
	Message: Could not find file '/App_Data/Sitecore/packages\Save Log-1.zip'.
	Source: mscorlib
	at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	at System.IO.FileInfo.get_Length()
	at Cognifide.PowerShell.Client.Applications.DownloadFile.OnLoad(EventArgs e)

**Comment by AdamNaj** [comment]
The issue is fixed long term in the platform as I'm now performing the mapped path rather than the string from the config. For now if you want to use the scripts - as a workaround for the scripts you can add the following code to the script beginning:

```powershell
$SitecorePackageFolder = [Sitecore.IO.FileUtil]::MapPath($SitecorePackageFolder);
```

and the script should be running...
