### ISSUE TITLE
Remove-Rendering command encounters exception on multiple deletions

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#452]
I am receiving the following error when I try to remove a rendering using Powershell ISE  

```c#
writeErrorStream : True
Exception : System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()
at System.Linq.Enumerable.<CastIterator>d__b1`1.MoveNext()
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
at Cognifide.PowerShell.Commandlets.Presentation.RemoveRenderingCommand.ProcessRenderings(Item item, LayoutDefinition layout, DeviceDefinition device, IEnumerable`1 renderings)
at Cognifide.PowerShell.Commandlets.Presentation.BaseRenderingCommand.ProcessLayout(Item item, LayoutDefinition layout, DeviceDefinition device)
at Cognifide.PowerShell.Commandlets.Presentation.BaseLayoutCommand.ProcessItem(Item item)
at Cognifide.PowerShell.Commandlets.BaseLanguageAgnosticItemCommand.ProcessRecord()
at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject :
CategoryInfo : NotSpecified: (:) [Remove-Rendering], InvalidOperationException
FullyQualifiedErrorId : System.InvalidOperationException,Cognifide.PowerShell.Commandlets.Presentation.RemoveRenderingCommand
ErrorDetails :
InvocationInfo : System.Management.Automation.InvocationInfo
PipelineIterationInfo : {0, 1}
PSMessageDetails :
```

Here is the code that I am using:

```powershell
cd 'master:\content\Home\News\Pages\Legislative-Updates' 

Get-ChildITem . | ForEach-Object {
      Write-Host "--- Updating": $_.ProviderPath
      Remove-Rendering -Path $_.ProviderPath -Placeholder "left-column"
      Write-Host "--- Completed Update  ----"
}
```

Can someone please tell me what I am doing wrong?

**Comment by Kasaku** [comment]
I don't think you are doing anything wrong in how you are using it, this comes down to the implementation of the command.

The command is iterating over `renderings`, which itself can be an iterator over `device.Renderings`. Because of this, if the collection is altered during this loop, an exception will be thrown.

Unable to try and test currently, but I believe the most straight-forward fix here would be to apply a `Reverse()` call to the iterator, which will allow the collection to be modified. Processing a list backwards to remove items is a common pattern. An alternative would be to use a .ToList() to turn `renderings` into a new list that is then processed.

**Comment by AdamNaj** [comment]
Thanks for taking the time to provide the solution to this! Merged.
