### ISSUE TITLE
Entering SC Content Editor throws NRE

### ISSUE THREAD

**Issue by jakub-malinowski** [SitecorePowerShell/Console#489]
When entering SC 8u4 CE, I get null reference exception, please see attached image and error from log

![powershellysod](https://cloud.githubusercontent.com/assets/14180554/9736222/3f3a4f64-5640-11e5-8939-e15b0658687a.png)

34516 15:33:41 ERROR Application error.
Exception: System.Web.HttpUnhandledException
Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.
Source: System.Web
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Nested Exception

Exception: System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
Source: mscorlib
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj)
   at Sitecore.Shell.Applications.ContentManager.ContentEditorPage.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Nested Exception

Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Cognifide.PowerShell
   at Cognifide.PowerShell.Core.Settings.ApplicationSettings.Load()
   at Cognifide.PowerShell.Core.Settings.ApplicationSettings.GetInstance(String applicationName, Boolean personalizedSettings)
   at Cognifide.PowerShell.Core.Host.ScriptSession..ctor(String applianceType, Boolean personalizedSettings)
   at Cognifide.PowerShell.Core.Host.ScriptSessionManager.GetSession(String persistentId, String applianceType, Boolean personalizedSettings)
   at Cognifide.PowerShell.Core.Host.ScriptSessionManager.NewSession(String applianceType, Boolean personalizedSettings)
   at Cognifide.PowerShell.Integrations.Pipelines.ContentEditorWarningScript.Process(GetContentEditorWarningsArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Shell.Applications.ContentManager.Editor.GetWarnings(Boolean hasSections)
   at Sitecore.Shell.Applications.ContentManager.Editor.Render(RenderContentEditorArgs args, Control parent)
   at Sitecore.Shell.Applications.ContentManager.ContentEditorForm.RenderEditor(Item item, Item root, Control parent, Boolean showEditor)
   at Sitecore.Shell.Applications.ContentManager.ContentEditorForm.UpdateEditor(Item folder, Item root, Boolean showEditor)
   at Sitecore.Shell.Applications.ContentManager.ContentEditorForm.Update()
   at Sitecore.Shell.Applications.ContentManager.ContentEditorForm.OnPreRendered(EventArgs e)

**Comment by AdamNaj** [comment]
Got this handled now. I'll get it up with all the other changes I'm currently working on.

**Comment by AdamNaj** [comment]
Fixed. Loading settings should never result in YSOD, but revert to defaults for particular value that was problematic..
