### ISSUE TITLE
Get-ItemWorkflowEvent Exceptions for Missing Parameters That Aren't Required

### ISSUE THREAD

**Issue by DavidMtbg** [SitecorePowerShell/Console#545]
Hi,

I was excited to see the inclusion of this cmdlet in SPE, but I am not able to get it to work as documented (unless I am missing something).  Here are example uses and how they are failing:

```powershell
PS master:\>Get-ItemWorkflowEvent -Id {110D559F-DEA5-42EA-9C1C-8A5DF7E70EF9}
 
 
writeErrorStream      : True
Exception             : System.ArgumentNullException: Value cannot be null.
                        Parameter name: name
                           at Sitecore.Diagnostics.Assert.ArgumentNotNull(Object argument, String argumentName)
                           at Sitecore.Configuration.Factory.GetDatabase(String name)
                           at Cognifide.PowerShell.Commandlets.BaseCommand.FindItemFromParameters(Item item, String path, String id, Language language, String databaseName)
                           at Cognifide.PowerShell.Commandlets.BaseItemCommand.ProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Get-ItemWorkflowEvent], ArgumentNullException
FullyQualifiedErrorId : System.ArgumentNullException,Cognifide.PowerShell.Commandlets.Workflows.GetItemWorkflowEventCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
PSMessageDetails      :
 
 
 
PS master:\>Get-ItemWorkflowEvent -Path master:\sitecore\content\home
 
 
writeErrorStream      : True
Exception             : System.ArgumentNullException: Value cannot be null.
                        Parameter name: name
                           at Sitecore.Diagnostics.Assert.ArgumentNotNull(Object argument, String argumentName)
                           at Sitecore.Configuration.Factory.GetDatabase(String name)
                           at Cognifide.PowerShell.Commandlets.BaseCommand.FindItemFromParameters(Item item, String path, String id, Language language, String databaseName)
                           at Cognifide.PowerShell.Commandlets.BaseItemCommand.ProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Get-ItemWorkflowEvent], ArgumentNullException
FullyQualifiedErrorId : System.ArgumentNullException,Cognifide.PowerShell.Commandlets.Workflows.GetItemWorkflowEventCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
PSMessageDetails      :
 
 
 
PS master:\>Get-ItemWorkflowEvent -Path master:\sitecore\content\home -Database master
 
 
writeErrorStream      : True
Exception             : System.Management.Automation.ParameterBindingException: Parameter set cannot be resolved using the specified named parameters.
                           at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
                           at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts,
                        CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          :
CategoryInfo          : InvalidArgument: (:) [Get-ItemWorkflowEvent], ParameterBindingException
FullyQualifiedErrorId : AmbiguousParameterSet,Cognifide.PowerShell.Commandlets.Workflows.GetItemWorkflowEventCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
PSMessageDetails      :
```

Thanks,
David

**Comment by michaellwest** [comment]
Hey @DavidMtbg, thank you for reporting the issue. Looks like I may have recently introduced a bug.

Try this:
```powershell
Get-ItemWorkflowEvent -Id {110D559F-DEA5-42EA-9C1C-8A5DF7E70EF9} -Database master
```

**Comment by DavidMtbg** [comment]
Hi @michaellwest, I did end up doing just that - thanks for your reply!

**Comment by AdamNaj** [comment]
Presumed fixed
