### ISSUE TITLE
Powershell Console - No Prompt

### ISSUE THREAD

**Issue by pvaartstra** [SitecorePowerShell/Console#628]
I installed the Powershell Sitecore Extensions 3.3 on my Sitecore 7.2 instance and when launching the Powershell Console, I get no input prompt.  Just the copyright header, and some spinning gears in the bottom.

My Sitecore version is 160123.

I do not see any related errors in the Sitecore log.

**Comment by AdamNaj** [comment]
Did you have any SPE version installed on it prior? If that is the case can you try opening it in private mode to see if you don't have any script cached in your browser?

**Comment by pvaartstra** [comment]
Yes, we upgraded from a previous version.  I followed the steps in your blog: http://blog.najmanowicz.com/2015/02/27/upgrading-your-sitecore-powershell-extensions-from-2-x-to-3-x-what-you-need-to-know/

Unfortunately we don’t have “In Private” enabled in our IE Tools (group policy).  I deleted my Temporary Internet files, and did a Ctrl-F5 to no avail.

**Comment by AdamNaj** [comment]
Is it possible for you to test it using a different browser than IE to test the functionality?

**Comment by pvaartstra** [comment]
Same symptom in Chrome 44.0.2403.157

**Comment by pvaartstra** [comment]
I did a network trace and found a 500 error on the call to PowershellWebService.asmx/ExecuteCommand

Then I finally found the corresponding error in the Eventlog:
Exception type: InvalidOperationException
    Exception message: Request format is unrecognized for URL unexpectedly ending in '/ExecuteCommand'

I see similar errors for the Sitecore /KeepAlive service.  So it doesn’t look like this is a SitecorePowerShell issue, rather it looks like I must have missed a step when switching from .Net 2 to .Net 4 during my recent Sitecore upgrade.

**Comment by AdamNaj** [comment]
Thanks for the update!

Let us know if you have managed to fix the problem. Feel free to close the issue if that is the case.

**Comment by AdamNaj** [comment]
I've qualified the issue initially as belonging to the "Rejected Issue" milestone simply for the purpose of taxonomy completeness. Should you find this to still be the problem on the SPE side, we will re-qualify it.

**Comment by pvaartstra** [comment]
Looking a little closer, those “keepalive” that I found are also related to the Powershell Console (not the Sitecore keepalive as I assumed).

POST /sitecore+modules/powershell/services/powershellwebservice.asmx/KeepAlive

I did a network trace, and both /KeepAlive and /ExecuteCommand are generating a 500 error with the following text:

System.InvalidOperationException: Request format is invalid: application/json; charset=utf-8.
   at System.Web.Services.Protocols.HttpServerProtocol.ReadParameters()
   at System.Web.Services.Protocols.WebServiceHandler.CoreProcessRequest()

StackOverflow articles regarding that error suggest adding the “System.Web.Script.Services.ScriptHandlerFactory” http handler.  I do not see that in the stock Sitecore 7.2 web.config.  Is this something that is supposed to be added for SitecorePowerShell console?

**Comment by janxl** [comment]
I have the same problem. Strangely enough only on my production server and not my acceptance server where powershell is working fine. The acceptance server is a single CA/CD server, whereas production is a dedicated CD. Otherwise they are practically identical.

I am running Sitecore.NET 7.2 (rev. 140526). I have installed Windows Powershell version 4.0. I have installed Sitecore PowerShell Extensions-4.0 for Sitecore 7. 

The POST PowerShell/Services/PowerShellWebService.asmx/ExecuteCommand returns a 500 error. Similarly, the sample commands in the Powershell ISE return a 500 error.

In my case the error message seems to be:

Exception: System.ArgumentOutOfRangeException
Message: Length cannot be less than zero.
Parameter name: length
Source: mscorlib
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Management.Automation.ExecutionContext.LoadAssembly(String name, String filename, Exception& error)
   at System.Management.Automation.ExecutionContext.AddAssembly(String name, String filename, Exception& error)
   at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean local)
   at System.Management.Automation.AutomationEngine..ctor(PSHost hostInterface, RunspaceConfiguration runspaceConfiguration, InitialSessionState iss)
   at System.Management.Automation.Runspaces.LocalRunspace.DoOpenHelper()
   at System.Management.Automation.Runspaces.RunspaceBase.CoreOpen(Boolean syncCall)
   at System.Management.Automation.PowerShell.Create(InitialSessionState initialSessionState)
   at Cognifide.PowerShell.Core.Host.ScriptingHost.get_Runspace()
   at Cognifide.PowerShell.Core.Host.ScriptSession..ctor(String applianceType, Boolean personalizedSettings)
   at Cognifide.PowerShell.Core.Host.ScriptSessionManager.GetSession(String persistentId, String applianceType, Boolean personalizedSettings)
   at Cognifide.PowerShell.Core.Host.ScriptSessionManager.NewSession(String applianceType, Boolean personalizedSettings)
   at Cognifide.PowerShell.Client.Applications.PowerShellIse.ClientExecute(ClientPipelineArgs args)

**Comment by janxl** [comment]
I have managed to fix the console to work on my prod environment. I compared all the dlls in the bin on prod against the dlls in the bin on accept and found a couple missing strangely enough (we inherited the sites from a different company).

I'm guessing either: Sitecore.Apps.Loader.dll or Sitecore.Speak.Charting.dll was missing and causing my error message to occur.

**Comment by michaellwest** [comment]
Thanks @janxl for getting back to us. You may find this gist helpful for comparing the files between two instances.

https://gist.github.com/michaellwest/309c6a49ff3946e984a39242353ebc4e

**Comment by AdamNaj** [comment]
Closing this issue because the responses suggests you guys were able to figure it out + a lack of activity for 4 months :)
