### ISSUE TITLE
NRE when inserting new component

### ISSUE THREAD

**Issue by mikkelkn** [SitecorePowerShell/Console#662]
We get this error when trying to insert a component. This is so far only a problem in our preprod environment. Powershell module has not been been installed in PROD yet. Dev end Test environments don't have this problem.

4704 10:16:18 ERROR Application error.
Exception: System.Web.HttpUnhandledException
Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.
Source: System.Web
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Nested Exception

Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Cognifide.PowerShell
   at Cognifide.PowerShell.Integrations.Pipelines.PageEditorExperienceButtonScript.Process(GetChromeDataArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.GetChromeData.GetChromeDataPipeline.Run(GetChromeDataArgs args)
   at Sitecore.Web.UI.WebControls.Placeholder.GetControlData(RenderingReference reference, Item item)
   at Sitecore.Shell.Applications.WebEdit.Palette.OnPreInit(EventArgs e)
   at System.Web.UI.Page.PerformPreInit()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by AlexKasaku** [comment]
What version of Sitecore and SPE are you running?

**Comment by mikkelkn** [comment]
Sitecore: 7.2
SPE: 4.0
PS: 4.0

**Comment by AdamNaj** [comment]
This is the same bug as is fixed in issue #672
