### ISSUE TITLE
Integration : Page Editor Experience Button pipeline conflicts with WFFM

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#672]
Reported by vince-scgeek on slack:

_The PageEditorExperienceButtonScript pipeline from SPE broke WFFM (non-mvc) on 8.1 upd3 today (when adding a form in Page Editor, palette.aspx started throwing a 500 error). After disabling it the issue disappeared_

**Comment by vince-geekcore** [comment]
This is the exception:

==
17536 12:11:23 ERROR Application error.
Exception: System.Web.HttpUnhandledException
Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.
Source: System.Web
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.sitecore_shell_applications_webedit_palette_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\2fb08551\13a10209\App_Web_blnevcen.1.cs:line 0
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Nested Exception

Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Cognifide.PowerShell
   at Cognifide.PowerShell.Integrations.Pipelines.PageEditorExperienceButtonScript.Process(GetChromeDataArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.GetChromeData.GetChromeDataPipeline.Run(GetChromeDataArgs args)
   at Sitecore.Web.UI.WebControls.Placeholder.GetControlData(RenderingReference reference, Item item)
   at Sitecore.Shell.Applications.WebEdit.Palette.OnPreInit(EventArgs e)
   at System.Web.UI.Page.PerformPreInit()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
===

**Comment by AdamNaj** [comment]
Should be fixed now.
