### ISSUE TITLE
Error while deleting script item with enabled events

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#691]
### Steps to Reproduce the Problem
1. Enable `Cognifide.PowerShell.Events.config` file
1. Open CE
1. Add new integration point
1. Open script library node (Functions) and add new script
1. Remove script 

  
### Expected Behavior 
Item removed without errors

### Actual Behavior
Error message thrown

Logs:

```
34240 11:06:53 INFO  Executing a Sitecore PowerShell Extensions script.
34240 11:06:53 ERROR One or more exceptions occurred while processing the subscribers to the 'item:deleted' event.
Exception[1]: System.ArgumentOutOfRangeException 
Message[1]: startIndex cannot be larger than length of string.
Parameter name: startIndex 
Source[1]: mscorlib 
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Cognifide.PowerShell.Core.Host.ScriptSession.GetDataContextSwitch(Item item)
   at Cognifide.PowerShell.Core.Host.ScriptSession.SetItemLocationContext(Item item)
   at Cognifide.PowerShell.Integrations.Tasks.ScriptedItemEventHandler.OnEvent(Object sender, EventArgs args)
   at Sitecore.Events.Event.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result) 


34240 11:06:53 ERROR Error while deleting items
Exception: System.AggregateException
Message: One or more exceptions occurred while processing the subscribers to the 'item:deleted' event.
Source: Sitecore.Kernel
   at Sitecore.Events.Event.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result)
   at Sitecore.Events.Event.RaiseEvent(String eventName, Object[] parameters)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Sitecore.Data.Engines.EngineCommand`2.RaiseEvent[TArgs](EventHandler`1 handlers, Func`2 argsCreator)
   at Sitecore.Data.Archiving.SqlArchive.DoArchiveItems(IEnumerable`1 items, ID archivalId)
   at Sitecore.Data.DataProviders.NullRetryer.Execute[T](Func`1 action, Action recover)
   at Sitecore.Data.Archiving.SqlArchive.ArchiveItem(Item item)
   at Sitecore.Shell.Framework.Pipelines.DeleteItems.Delete(List`1 items)
   at Sitecore.Shell.Framework.Pipelines.DeleteItems.Execute(ClientPipelineArgs args)
```

**Comment by AdamNaj** [comment]
Hi Alan,

Unfortunately I cannot reproduce this behaviour :(
Can you verify that it's still the case for you with the latest code?

**Comment by alan-null** [comment]
@AdamNaj I cannot reproduce it as well.
