### ISSUE TITLE
Get-Item and Get-ChildItem should not log PipelineStoppedExceptions - those are pipeline stopping signals - not errors

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#831]
The following script:
```powershell
Get-ChildItem master:\ | Select-Object -First 1
```

Would log this error:
```ManagedPoolThread #1 14:27:56 ERROR Error while executing GetChildItems(string path='master:/sitecore', string recurse='False')
Exception: System.Management.Automation.PipelineStoppedException
Message: The pipeline has been stopped.
Source: System.Management.Automation
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.Internal.Pipe.AddToPipe(Object obj)
   at System.Security.SecurityContext.Run(SecurityContext securityContext, ContextCallback callback, Object state)
   at System.Management.Automation.MshCommandRuntime.WriteObject(Object sendToPipeline)
   at System.Management.Automation.Cmdlet.WriteObject(Object sendToPipeline)
   at System.Management.Automation.Provider.CmdletProvider.WriteItemObject(Object item, String path, Boolean isContainer)
   at Cognifide.PowerShell.Core.Provider.PsSitecoreItemProvider.WriteItem(Item item)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Cognifide.PowerShell.Core.Provider.PsSitecoreItemProvider.GetChildItemsHelper(Item item, Boolean recurse, WildcardPattern wildcard, String[] language, Int32 version, UInt32 currentDepth, UInt32 depth)
   at Cognifide.PowerShell.Core.Provider.PsSitecoreItemProvider.GetChildItemsWithDepth(String path, Boolean recurse, UInt32 depth)
```

Where it should not.

**Comment by michaellwest** [comment]
I noticed this error a few days ago. Thanks for reporting it.

**Comment by AdamNaj** [comment]
Fixed
