### ISSUE TITLE
Error while running scheduled task from Task Manager

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#890]
Seeing the following error appear in the SPE.log after running the task.

```
ManagedPoolThread #7 11:47:31 INFO  Executing a script in ScriptSession '$scriptSession$|rf3eudd4hmje2vgdy1l3xzvs|5c15eae0-4166-421c-9b1c-154d5b597b78'.
ManagedPoolThread #7 11:47:31 INFO  Executing PsSitecoreItemProvider5.Start(providerInfo='Sitecore')
ManagedPoolThread #7 11:47:31 INFO  Executing PsSitecoreItemProvider5.Start(providerInfo='Sitecore')
ManagedPoolThread #7 11:47:31 INFO  Executing a script in ScriptSession ''.
ManagedPoolThread #7 11:47:31 INFO  The script execution in ScriptSession '' completed in 2 ms.
ManagedPoolThread #7 11:47:31 ERROR Error while performing timed 'script execution in ScriptSession '$scriptSession$|rf3eudd4hmje2vgdy1l3xzvs|5c15eae0-4166-421c-9b1c-154d5b597b78'' operation within 141 ms. Exception logged at operation origin point.
ManagedPoolThread #7 11:47:31 ERROR Error while executing PowerShell script.
Exception: System.Management.Automation.CmdletInvocationException
Message: There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was: 
              ...               
Source: System.Management.Automation
   at System.Management.Automation.Internal.PipelineProcessor.DoStepItems(Object input, Hashtable errorResults, Boolean enumerate)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ApplyFormatting(Object o)
   at Microsoft.PowerShell.Commands.Internal.Format.OutCommandInner.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()

Nested Exception

Exception: System.Management.Automation.PSInvalidOperationException
Message: There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was: 
              ...               
Source: System.Management.Automation
   at System.Management.Automation.ScriptBlock.GetContextFromTLS()
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at Microsoft.PowerShell.Commands.Internal.Format.MshExpression.GetValue(PSObject target, Boolean eatExceptions)
   at Microsoft.PowerShell.Commands.Internal.Format.MshExpression.GetValues(PSObject target, Boolean expand, Boolean eatExceptions)
   at Microsoft.PowerShell.Commands.Internal.Format.ComplexControlGenerator.ExecuteFormatTokenList(TraversalInfo level, PSObject so, List`1 formatTokenList, List`1 formatValueList)
   at Microsoft.PowerShell.Commands.Internal.Format.ComplexControlGenerator.ExecuteFormatControl(TraversalInfo level, ControlBase control, PSObject so, List`1 formatValueList)
   at Microsoft.PowerShell.Commands.Internal.Format.ComplexViewGenerator.GenerateComplexViewEntryFromDataBaseInfo(PSObject so, Int32 enumerationLimit)
   at Microsoft.PowerShell.Commands.Internal.Format.ComplexViewGenerator.GeneratePayload(PSObject so, Int32 enumerationLimit)
   at Microsoft.PowerShell.Commands.Internal.Format.OutOfBandFormatViewManager.GenerateOutOfBandData(TerminatingErrorContext errorContext, MshExpressionFactory expressionFactory, TypeInfoDataBase db, PSObject so, Int32 enumerationLimit, Boolean useToStringFallback, List`1& errors)
   at Microsoft.PowerShell.Commands.Internal.Format.InnerFormatShapeCommand.ProcessOutOfBandObjectOutsideDocumentSequence(PSObject so)
   at Microsoft.PowerShell.Commands.Internal.Format.InnerFormatShapeCommand.ProcessObject(PSObject so)
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by AdamNaj** [comment]
I believe this was fixed as part of #791, I can no longer reproduce it.
