### ISSUE TITLE
Installation Powershell package with sitecore publishing service 2.0 => Failled

### ISSUE THREAD

**Issue by RomainDou** [SitecorePowerShell/Console#892]
Hello,

When we tried to install the powershell package, we have this following error:

ManagedPoolThread #7 12:34:24 ERROR Installation failed: System.ArgumentNullException: A non-invariant language must be specified.
Parameter name: language
   at Sitecore.Framework.Publishing.Locators.ItemVariantLocator..ctor(String store, Guid id, Language language, Version version)
   at Sitecore.Publishing.Service.PublishManager.EmitItemEvent(Item item, DateTime timestamp, ItemOperationRestrictions restrictions, PublisherOperationType operation, String itemPath)
   at Sitecore.Publishing.Service.PublishManager.DataEngine_SavedItem(Object sender, ExecutedEventArgs`1 e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Sitecore.Data.Engines.EngineCommand`2.RaiseEvent[TArgs](EventHandler`1 handlers, Func`2 argsCreator)
   at Sitecore.Data.Engines.EngineCommand`2.Execute()
   at Sitecore.Data.Engines.DataEngine.SaveItem(Item item)
   at Sitecore.Data.Managers.ItemProvider.SaveItem(Item item)
   at Sitecore.Data.Managers.DefaultItemManager.ExecuteAndReturnResult[TArgs,TResult](String pipelineName, String pipelineDomain, Func`1 pipelineArgsCreator, Func`1 fallbackResult)
   at Sitecore.Data.Managers.DefaultItemManager.SaveItem(Item item)
   at Sitecore.Data.Items.ItemEditing.AcceptChanges(Boolean updateStatistics, Boolean silent)
   at Sitecore.Data.Items.ItemEditing.EndEdit(Boolean updateStatistics, Boolean silent)
   at Sitecore.Install.Items.ItemInstaller.InstallItem(BehaviourOptions installOptions, Item targetItem, ItemReference item, XmlVersionParser parser, Boolean& removeVersions)
   at Sitecore.Install.Items.ItemInstaller.GetVersionInstallMode(PackageEntry entry, ItemReference reference, XmlVersionParser parser, ItemInstallerContext context, Boolean& removeVersions)
   at Sitecore.Install.Items.ItemInstaller.InstallEntry(PackageEntry entry)
   at Sitecore.Install.Items.ItemInstaller.Flush()
   at Sitecore.Install.Framework.SinkDispatcher.Flush()
   at Sitecore.Install.Utils.EntrySorter.Flush()
   at Sitecore.Install.Framework.EntryBuilder.Flush()
   at Sitecore.Install.Zip.PackageReader.Populate(ISink`1 sink)
   at Sitecore.Install.Installer.InstallPackage(String path, Boolean registerInstallation, ISource`1 source, IProcessingContext context)
   at Sitecore.Install.Installer.InstallPackage(String path, ISource`1 source, IProcessingContext context)
   at Sitecore.Install.Installer.InstallPackage(String path, IProcessingContext context)
   at Sitecore.Shell.Applications.Install.Dialogs.InstallPackage.InstallPackageForm.AsyncHelper.<Install>b__4()
   at Sitecore.Shell.Applications.Install.Dialogs.InstallPackage.InstallPackageForm.AsyncHelper.CatchExceptions(ThreadStart start)

How install this package with Sitecore publishing service 2.0 ?

Thanks in advance.

Best regards,

Romain

**Comment by michaellwest** [comment]
Hi @RomainDou, I've had to disable the `Sitecore.Publishing.Service.config` during installation to get past this issue.

**Comment by RomainDou** [comment]
Many thanks !!!!!!
It's ok now.

Best regards,

Romain
