### ISSUE TITLE
Exception on using -ShowWindow argument

### ISSUE THREAD

**Issue by phaniav** [SitecorePowerShell/Console#895]
I received following exception when used the below command. The issue is when I type the -ShowWindow in the end.

Get-Help Get-Content -ShowWindow

![image](https://cloud.githubusercontent.com/assets/3968213/26466314/fa3865d2-41ab-11e7-8c83-cdcca3ffe9e2.png)

Below exception is logged in lg file and application will restart

`Message: The current configuration system does not support user-scoped settings.
Source: System
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at Microsoft.Management.UI.Internal.HelpWindowSettings.get_HelpSynopsysDisplayed()
   at Microsoft.Management.UI.Internal.HelpParagraphBuilder.AddTextToParagraphBuilder()
   at Microsoft.Management.UI.Internal.HelpViewModel..ctor(PSObject psObj, Paragraph documentParagraph)
   at Microsoft.Management.UI.HelpWindow..ctor(PSObject helpObject)
   at Microsoft.PowerShell.Commands.Internal.HelpWindowHelper.<>c__DisplayClass4.<ShowHelpWindow>b__2()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`

**Comment by AdamNaj** [comment]
This functionality is not implemented as we cannot create Windows window within the browser. I don't believe it's possible for us to hook into Get-Help for this.
If you want an experience similar to what the result of the command would be you can type your command in ISE and press `Ctrl`+`Enter`.

![help-interactive](https://cloud.githubusercontent.com/assets/1209953/26492893/e19e2e60-4216-11e7-8166-15b1df84a838.gif)
