### ISSUE TITLE
Installation error - Access to the path 'F:\install\6889A0D18ABC47A0993ED1E607B363F2' is denied.

### ISSUE THREAD

**Issue by vrkmajeti** [SitecorePowerShell/Console#944]
We tried to install SPE 4.6 for sitcore 8 on sitecore 8.2 udpate 4 using the install wizard. But the install failed with the error - "Access to the path 'F:\install\6889A0D18ABC47A0993ED1E607B363F2' is denied."
Computer doesn't have the F drive. but SPE installation is looking for F drive. Please advice.
![spe install fails](https://user-images.githubusercontent.com/1881988/30626624-fdaf900c-9d98-11e7-8560-fdd708192816.png)

**Comment by jammykam** [comment]
@vrkmajeti: I've seen this issue before when the value of **tempFolder** is set to an absolute path (e.g. C:\temp). 

The default value should be `<sc.variable name="tempFolder" value="/temp"/>`. Double check your configuration and ensure that only a relative path is used.

**Comment by vrkmajeti** [comment]
@jammykam Yes, i see the same default setting value for tempFolder. Below are the only 2 references of tempFolder word in showconfig.aspx
<sc.variable name="tempFolder" value="/temp"/>
<setting name="TempFolder" value="/temp"/>

here is the full error trace:

> ManagedPoolThread #1 04:23:02 ERROR Installation failed: System.UnauthorizedAccessException: Access to the path 'F:\install\2F39FEF5EA7A4F9FA3F5F5E2007FA668' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Sitecore.Install.Files.FileInstaller.Install(Boolean allowOverwrite, String path, PackageEntry entry)
   at Sitecore.Install.Files.FileInstaller.Put(PackageEntry entry)
   at Sitecore.Install.Framework.SinkDispatcher.Put(PackageEntry entry)
   at Sitecore.Install.Utils.EntrySorter.Flush()
   at Sitecore.Install.Framework.EntryBuilder.Flush()
   at Sitecore.Install.Zip.PackageReader.Populate(ISink`1 sink)
   at Sitecore.Install.Installer.InstallPackage(String path, Boolean registerInstallation, ISource`1 source, IProcessingContext context)
   at Sitecore.Install.Installer.InstallPackage(String path, ISource`1 source, IProcessingContext context)
   at Sitecore.Shell.Applications.Install.Dialogs.InstallPackage.InstallPackageForm.AsyncHelper.<Install>b__4()
   at Sitecore.Shell.Applications.Install.Dialogs.InstallPackage.InstallPackageForm.AsyncHelper.CatchExceptions(ThreadStart start)
ManagedPoolThread #1 04:24:18 ERROR Installation failed: System.UnauthorizedAccessException: Access to the path 'F:\install\B3964AF3C9114A47ADF9D08280942E9B' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Sitecore.Install.Files.FileInstaller.Install(Boolean allowOverwrite, String path, PackageEntry entry)
   at Sitecore.Install.Files.FileInstaller.Put(PackageEntry entry)
   at Sitecore.Install.Framework.SinkDispatcher.Put(PackageEntry entry)
   at Sitecore.Install.Utils.EntrySorter.Flush()
   at Sitecore.Install.Framework.EntryBuilder.Flush()
   at Sitecore.Install.Zip.PackageReader.Populate(ISink`1 sink)
   at Sitecore.Install.Installer.InstallPackage(String path, Boolean registerInstallation, ISource`1 source, IProcessingContext context)
   at Sitecore.Install.Installer.InstallPackage(String path, ISource`1 source, IProcessingContext context)
   at Sitecore.Shell.Applications.Install.Dialogs.InstallPackage.InstallPackageForm.AsyncHelper.<Install>b__4()
   at Sitecore.Shell.Applications.Install.Dialogs.InstallPackage.InstallPackageForm.AsyncHelper.CatchExceptions(ThreadStart start)

**Comment by vrkmajeti** [comment]
We changed the app pool to run under LocalSystem account temporarily to install the package and installation succeeded without any errors. Error was partially misleading but it is resolved now and this issue can be closed.
