### ISSUE TITLE
Show-ListView throws error on export using custom object

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#980]
The following script encounters an error when exporting Excel and Csv.

```powershell
$startPath = "master:/sitecore/content/Home"
$list = [System.Collections.ArrayList]@()
$items = Get-ChildItem $startPath
$list = $items | ForEach-Object { $list = [System.Collections.ArrayList]@() } { $list.Add([PSCustomObject]@{"Name"=$_.DisplayName }) | Out-Null } { $list }
$list | Show-ListView
```

**Error:**
> Exception: System.ArgumentNullException
Message: Value cannot be null.
Parameter name: source
Source: System.Core
   at System.Linq.Enumerable.Cast[TResult](IEnumerable source)
   at Cognifide.PowerShell.Client.Applications.PowerShellResultViewerList.SetVariables(ScriptSession session, Message message)
   at Cognifide.PowerShell.Client.Applications.PowerShellResultViewerList.ExecuteScriptJob(Item scriptItem, ScriptSession scriptSession, Message message, Boolean autoDispose)
   at Cognifide.PowerShell.Client.Applications.PowerShellResultViewerList.ExportResults(Message message)
   at Cognifide.PowerShell.Client.Applications.PowerShellResultViewerList.HandleMessage(Message message)
   at Sitecore.Shell.Framework.Commands.MessageCommand.Execute(CommandContext context)
   at Sitecore.Web.UI.Sheer.ClientPage.Dispatch(String command)
   at Sitecore.Web.UI.Sheer.ClientPage.RaiseEvent()
   at Sitecore.Web.UI.Sheer.ClientPage.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by michaellwest** [comment]
Turns out the issue has to do with the the lack of support for `PSCustomObject` types. I added a check for custom types so the property names would be queried.

**Comment by michaellwest** [comment]
Implemented.
