### ISSUE TITLE
Web API Initialization is not tread safe

### ISSUE THREAD

**Issue by IvanLieckens** [SitecorePowerShell/Console#997]
### Expected Behavior

No exceptions

### Actual Behavior

16612 2018:04:13 23:47:48 ERROR Application error.
Exception: System.InvalidOperationException
Message: Collection was modified; enumeration operation may not execute.
Source: mscorlib
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Cognifide.PowerShell.Core.Settings.Authorization.ServiceAuthorizationManager.IsUserAuthorized(String serviceName, String userName) in C:\Projects\sitecorepowershell\Trunk\Cognifide.PowerShell\Core\Settings\Authorization\ServiceAuthorizationManager.cs:line 48
   at Cognifide.PowerShell.Console.Services.RemoteScriptCall.ProcessRequest(HttpContext context) in C:\Projects\sitecorepowershell\Trunk\Cognifide.PowerShell\sitecore modules\PowerShell\Services\RemoteScriptCall.ashx.cs:line 83
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

### Steps to Reproduce the Problem

Rapidly fire multiple requests at the Web API endpoint of SPE after Sitecore startup. It appears the initialization isn't thread safe and causes an exception on the first calls.

SPE 4.7 on Sitecore 8.2.6

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [X] Asked questions on the Sitecore Slack Chat channel.
   Together with Adam I arrived at the stacktrace above.
 
 - [X] Reviewed questions and answers on the Sitecore Stack Exchange.
   No responses, question is at: https://sitecore.stackexchange.com/questions/11337/spe-remote-script-call-nullreference-exception

**Comment by michaellwest** [comment]
Duplicated the issue by restarting the website from IIS and then running the following script:

```powershell
Invoke-WebRequest -UseBasicParsing -Uri "http://sc827/sitecore/service/keepalive.aspx" | Select-Object -ExpandProperty StatusDescription

$jobs = [System.Collections.ArrayList]@()
foreach($index in 1..5) {
    $job = Start-Job -ScriptBlock {
        $url = "http://sc827/-/script/v2/master/DoSomething?user=admin&password=b"
        Invoke-WebRequest -UseBasicParsing -Uri $url | Select-Object -ExpandProperty Content
    }

    $jobs.Add($job) > $null
}

$jobs | Wait-Job
$jobs | Receive-Job
```

**Comment by michaellwest** [comment]
@IvanLieckens Hopefully the concurrent dictionary resolves the issue for you.

**Comment by michaellwest** [comment]
Also fixed the issue where it says you are not authorized on the first attempt.
